repos:
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: PHP CS Fixer
        entry: composer lint
        language: system
        pass_filenames: false
      - id: phpstan
        name: PHPStan
        entry: composer analyse
        language: system
        pass_filenames: false
      - id: phpunit
        name: PHPUnit
        entry: composer test
        language: system
        pass_filenames: false
