version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.25
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3307}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-menu}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-menu}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    profiles:
      - tools

volumes:
  mysql_data:
  redis_data:
